import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function HtmlListas() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Списки</h1>

        <div>
          <p>
            маркированный список &lt;ul&gt; каждый элемент списка &lt;li&gt;
            отмечается маркером
          </p>
          <ul>
            <li>Microsoft</li>
            <li>Google</li>
            <li>Apple</li>
            <li>IBM</li>
          </ul>
        </div>
        <div>
          <p>
            нумерованный список &lt;ol&gt; каждый элемент списка &lt;li&gt;
            отмечается цифрой,
          </p>
          <ol>
            <li>Microsoft</li>
            <li>Google</li>
            <li>Apple</li>
            <li>IBM</li>
          </ol>
        </div>
        <div>
          <p>
            список определений &lt;dl&gt; состоит из пар термин &lt;dt&gt;
            &lt;dd&gt; определение. Каждый список представляет собой контейнер,
            внутри которого располагаются элементы списка или пары
            термин-определение.
          </p>
          <dl>
            <dt>Режиссер:</dt>
            <dd>Петр Точилин</dd>
            <dt>В ролях:</dt>
            <dd>Андрей Гайдулян</dd>
            <dd>Алексей Гаврилов</dd>
            <dd>Виталий Гогунский</dd>
            <dd>Мария Кожевникова</dd>
          </dl>
        </div>
        <div>
          <a href="./">Назад</a>
        </div>
      </main>
    </>
  );
}
