import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function HtmlTable() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Таблицы</h1>

        <table border="50">
          <thead>
            <tr>
              <th>Колонка 1</th>
              <th>Колонка 2</th>
              <th>Колонка 3</th>
              <th>Колонка 4</th>
              <th>Колонка 5</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>данные 1</td>
              <td>данные 2</td>
              <td>данные 3</td>
              <td>данные 4</td>
              <td>данные 5</td>
            </tr>
          </tbody>
          <tbody>
            <tr>
              <td>данные 1</td>
              <td>данные 2</td>
              <td>данные 3</td>
              <td>данные 4</td>
              <td>данные 5</td>
            </tr>
          </tbody>
          <tbody>
            <tr>
              <td>данные 1</td>
              <td>данные 2</td>
              <td>данные 3</td>
              <td>данные 4</td>
              <td>данные 5</td>
            </tr>
          </tbody>
        </table>

        <div>
          <a href="./">Назад</a>
        </div>
      </main>
    </>
  );
}
