import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function HtmlImg() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Image</h1>
        <p>
          Чтобы отобразить какую-нибудь картинку на веб-странице, необходим тег
          &lt;img&gt;. Данный тег является одиночным и строчным, а также имеет
          два обязательных атрибута src и alt. При помощи атрибута src
          указывается путь к картинке. При помощи атрибута alt указывается
          альтернативный текст для картинки. Если картинка по каким либо
          причинам не отобразится на веб-странице, то вместо нее вы увидите
          альтернативный текст. Также для изображения рекомендуется указывать
          ширину и высоту, это позволит браузеру быстрее загружать изображения
          на веб-страницу. Указывать ширину и высоту можно при помощи каскадных
          таблиц стилей, либо при помощи атрибутов width (ширина) и height
          (высота).
        </p>
        <p>
          &lt;img src="image.jpg" alt="Альтернативный текст" width="300"
          height="250"&gt;&lt;/img&gt;
        </p>
        <div>
          <a href="./">Назад</a>
        </div>
      </main>
    </>
  );
}
