import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <ol>
          <li>
            <a href="/html">
              HTML <img src="/img/HTML.png" alt="html" width={36} height={36} />
            </a>
          </li>
          <li>
            <a href="/css">
              CSS <img src="/img/CSS.jpeg" alt="css" width={36} height={36} />
            </a>
          </li>
          <li>
            <a href="/js">
              JS <img src="/img/JS.png" alt="js" width={36} height={36} />
            </a>
          </li>
          <li>
            <a href="/ts">
              TS <img src="/img/TS.jpeg" alt="ts" width={36} height={36} />
            </a>
          </li>
          <li>
            <a href="/angular">
              Angular{" "}
              <img
                src="/img/Angular.jpeg"
                alt="angular"
                width={36}
                height={36}
              />
            </a>
          </li>
          <li>
            <a href="/react">
              React{" "}
              <img
                src="https://oneteamsolutions.in/blogoneteam/wp-content/uploads/2020/05/REACT-JS-KOCHI.png"
                alt="react"
                width={36}
                height={36}
              />
            </a>
          </li>
        </ol>
        <progress>----</progress>
      </main>
    </>
  );
}
