import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function HtmlParrafo() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <form action="Анкеточка" method="post">
          <h1>Анкеточка</h1>
          <label htmlFor="name">Имя: </label>
          <input type="text" />
          <br />
          <br />
          <label htmlFor="surname">Фамилия: </label>
          <input type="text" />
          <br />
          <br />
          <label htmlFor="address">Адрес по прописке: </label>
          <input type="text" />
          <br />
          <br />
          <label htmlFor="zip">Почтовый код: </label>
          <input type="number" />
          <br />
          <br />
          <label htmlFor="date">Дата рождения: </label>
          <input type="date" name="дата рождения" id="дата рождения" />
          <br />
          <br />
          <label htmlFor="email">Электронная почта: </label>
          <input type="email" name="электронная почта" id="электронная почта" />
          <br />
          <br />
          <label htmlFor="product">Продукт: </label>
          <select name="product" id="product">
            <option value="яблоко">Яблоко</option>
            <option value="банан">Банан</option>
            <option value="груша">Груша</option>
            <option value="киви">Киви</option>
          </select>
          <br />
          <br />
          <label htmlFor="comments">Коментарии: </label>
          <textarea name="comments" id="comments" cols={50} rows={5}></textarea>
          <br /> <br />
          <input type="submit" value="Отправить это" />
        </form>
        <br />
        <br />

        <label htmlFor=""></label>
        <input type="time" name="" id="" />
        <br />
        <br />

        <iframe src="" frameborder="0"></iframe>

        <div>
          <a href="./">Назад</a>
        </div>
      </main>
    </>
  );
}
